Repository minibolt-guide/minibolt, pull requests merged in 2023-01, with the labels that each got.

#21 [UPDATE] Added recommended command to signature check
  guide/bitcoin/bitcoin-client.md
Labels: feature request

#20 [NEW BONUS GUIDE] SSH keys - a safer way to SSH authentification in your system
  guide/bitcoin/desktop-wallet.md
  guide/bonus/system/index.md
  guide/bonus/system/ssh-keys.md
  guide/system/configuration.md
  guide/system/operating-system.md
  guide/system/preparations.md
  guide/system/privacy.md
  guide/system/remote-access.md
Labels: future bonus guide

#24 [NEW SECTION] Sparrow Terminal: Add mixing section
  guide/bonus/bitcoin/sparrow-server.md
Labels: feature request

#23 [UPDATE MAIN GUIDE] send bitcoind logs to stdout and let systemd pick them up
  guide/bitcoin/bitcoin-client.md
  guide/bonus/bitcoin/electrum-personal-server.md
  resources/.bash_aliases
Labels: feature request

#29 [UPDATE MAIN GUIDE] Add variables $VERSION to agility the installing and updating process of the services + improvements
  guide/bitcoin/bitcoin-client.md
  guide/bitcoin/electrum-server.md
  guide/lightning/lightning-client.md
  guide/lightning/mobile-app.md
Labels: new feature

#31 [DEV Improvement] set up a local dev environment
  .gitignore
  Gemfile
Labels: improvement

#32 [General Improvement] cleanup GH Pages
  _config.yml
Labels: improvement
